<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Version>1.0.2</Version>
    <VersionPrefix>1.0.2</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassroomToolkit.Domain\ClassroomToolkit.Domain.csproj" />
    <ProjectReference Include="..\ClassroomToolkit.Infra\ClassroomToolkit.Infra.csproj" />
  </ItemGroup>
</Project>
